name: Link Config Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  local-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install

      - name: Test link config & format
        run: pnpm test
